name: hist_gradient_boosting
params:
  learning_rate: 0.1
  max_iter: 100
  max_leaf_nodes: 31
  max_depth: null
  min_samples_leaf: 20
  l2_regularization: 0.0
  max_bins: 255
  categorical_features: null
  monotonic_cst: null
  warm_start: false
  early_stopping: auto
  scoring: loss
  validation_fraction: 0.1
  n_iter_no_change: 10
  tol: 1e-07
