name: hist_gradient_boosting
params:
  l2_regularization: 0.9202038272323202
  learning_rate: 0.027864170616690123
  max_iter: 190
  max_leaf_nodes: 28
  min_samples_leaf: 42
  n_iter_no_change: 10
  tol: 1e-07
