name: lightgbm
params:
  boosting_type: gbdt
  objective: binary
  metric: binary_logloss
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: 0
  min_data_in_leaf: 6
  min_sum_hessian_in_leaf: 11
  n_estimators: 100
  max_depth: -1
  min_split_gain: 0.0
  min_child_weight: 0.001
  min_child_samples: 20
  subsample: 1.0
  subsample_freq: 0
  colsample_bytree: 1.0
  reg_alpha: 0.0
  reg_lambda: 0.0
  n_jobs: -1
  silent: true
  importance_type: split
