name: xgboost
params:
  colsample_bytree: 0.7351421288846683
  learning_rate: 0.07926004251101824
  max_depth: 8
  n_estimators: 96
  reg_alpha: 0.06779661113890172
  reg_lambda: 9.088250624476464
  subsample: 0.9437099479618614
  random_state: 42
  n_jobs: -1
